// 대시보드 카드 정의. status: 'live' | 'pending'
// pending 카드는 reason 필드로 사유를 표시한다.
const CARDS = [
  {
    id: 'short-selling',
    icon: '📉',
    title: '한국 공매도',
    desc: '한국 상장 종목의 공매도 잔고 대시보드. 종목별 공매도 비중 전일 대비 변화 추이.',
    tag: 'CLOUD',
    status: 'pending',
    reason: 'KRX 통계 화면이 회원 로그인 필수로 전환되어 자동 스크래핑이 불가합니다. 공공데이터포털(금융위원회) 쪽에 대체 API가 있는지 추가 조사 중입니다.',
  },
  {
    id: 'alert-screener',
    icon: '⚡',
    title: '투자주의/경고 스크리너',
    desc: '코스피·코스닥 전종목 장중 시세 기반 투자주의/경고/위험 종목 사전·해제 편입.',
    tag: 'LIVE',
    status: 'pending',
    reason: 'KRX 시장경보 조회 화면이 로그인 필수로 전환되었습니다. 대체 데이터 소스 확인이 필요합니다.',
  },
  {
    id: 'futures-oi',
    icon: '📐',
    title: '주식선물 미결제약정 현황',
    desc: 'KRX 주식선물 종목의 미결제약정 잔량 랭킹과 전일대비 증감.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-oi.json',
    render: 'renderFuturesOi',
  },
  {
    id: 'futures-basis',
    icon: '📏',
    title: '주식선물 베이시스 (콘탱고/백워데이션)',
    desc: '선물 상장 종목의 선물가 vs 현물가 괴리율. 콘탱고·백워데이션 상위 종목.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-basis.json',
    render: 'renderFuturesBasis',
  },
  {
    id: 'investor-flow',
    icon: '🔄',
    title: '수급 주체 전환 스크리너',
    desc: '연기금·외국인·투신·사모 등 투자주체별 순매수대금. 최근 3거래일 누적 vs 직전 5거래일 비교.',
    tag: 'LIVE',
    status: 'pending',
    reason: 'KRX 투자자별 매매동향 화면이 로그인 필수로 전환되었습니다. 대체 데이터 소스 확인이 필요합니다.',
  },
  {
    id: 'nvda-earnings',
    icon: '🎯',
    title: '엔비디아 실적 전후 등락률',
    desc: 'NVDA 실적 발표를 D+0으로 놓고 D-1~D+4 동안 NVDA·SOXX·SK하이닉스·삼성전자·코스피가 어떻게 움직였는지 최근 분기를 비교.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'nvda-earnings-reaction.json',
    render: 'renderNvdaEarnings',
  },
  {
    id: 'etf-rebalance-schedule',
    icon: '🗓️',
    title: '패시브 ETF 정기변경 일정',
    desc: '국내 주요 패시브 ETF의 정기변경(리밸런싱) 일정·산출·운용사 별 체크. KRX·운용사 홈페이지 공지 기반 캘린더.',
    tag: 'CLOUD',
    status: 'pending',
    reason: '지수산출기관·운용사별 공지가 제각각이라 정기 크롤링 대상 URL을 확정하는 조사가 필요합니다.',
  },
  {
    id: 'sector-etf-rebalance',
    icon: '🏛️',
    title: '섹터/테마 ETF 리밸런싱 감지',
    desc: '섹터·테마 ETF 49종(액티브 포함)의 전날 대비 오늘 보유수량 변화 매일 감지. 신규 편입/편출 종목 탐지.',
    tag: 'LIVE',
    status: 'pending',
    reason: 'ETF PDF(구성종목) 데이터를 매일 비교해야 합니다. 운용사별 PDF 제공 방식 조사가 필요합니다.',
  },
  {
    id: 'export-data',
    icon: '📦',
    title: '수출데이터 일평균',
    desc: '관세청(TRASS) 잠정 수출 33개 품목을 영업일 평균 기준으로 추적.',
    tag: 'LIVE',
    status: 'pending',
    reason: '공공데이터포털(관세청 수출입무역통계) API 신청이 필요합니다. data.go.kr에서 무료 신청 가능 — 신청해주시면 바로 연동합니다.',
  },
  {
    id: 'capital-increase',
    icon: '🏢',
    title: '유무상증자 기준일',
    desc: 'DART 전자공시 수집으로 유상증자·무상증자·주주배정 기준일을 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: ['dart-capital-increase-paid.json', 'dart-capital-increase-free.json'],
    render: 'renderCapitalIncrease',
  },
  {
    id: 'convertible-bond',
    icon: '🔁',
    title: '전환청구권 신주상장 캘린더',
    desc: 'CB(전환사채) 발행 결정 공시를 수집해 전환가액·전환청구기간을 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-convertible-bond.json',
    render: 'renderConvertibleBond',
  },
  {
    id: 'treasury-stock',
    icon: '💰',
    title: '자사주 매입 캘린더',
    desc: 'DART 자사주 신고·체결내역과 주요사항 보고서를 걸어, 지금 자사주를 사고 있거나 앞으로 살 계획인 회사를 취득기간 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-treasury-stock.json',
    render: 'renderTreasuryStock',
  },
  {
    id: 'insider-plan',
    icon: '👤',
    title: '내부자 사전공시',
    desc: '임원·주요주주 거래계획보고서(자본시장법 §173의3)를 수집해 거래 예정기간을 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-insider-plan.json',
    render: 'renderInsiderPlan',
  },
  {
    id: 'us-market-brief',
    icon: '🌙',
    title: '전일 미국장 시황 브리핑',
    desc: '간밤 미국 증시 시황 요약 브리핑. 주요 지수·금리·환율·원자재 자동 수집.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'us-market-brief.json',
    render: 'renderMarketBrief',
  },
  {
    id: 'us-new-highs-20d',
    icon: '📈',
    title: 'US 미국장 20일 신고가',
    desc: 'S&P500 전종목 중 20일 신고가 경신 종목 스크리너.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-20d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'us-new-highs-50d',
    icon: '🏦',
    title: '미국장 50일 신고가 (대형주)',
    desc: '다우30 + 나스닥100 대형주 중 50일 신고가 경신 종목 스크리너.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-50d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'us-earnings',
    icon: '🇺🇸',
    title: 'US 기업 실발 전후',
    desc: '미국 상장 기업의 실적 발표 전후 주가·이벤트 분석 대시보드.',
    tag: 'CLOUD',
    status: 'pending',
    reason: '무료로 안정적인 미국 실적 캘린더 API(Finnhub 등) 키가 필요합니다. 발급해주시면 연동합니다.',
  },
  {
    id: 'kr-earnings',
    icon: '🇰🇷',
    title: 'KR 기업 실발 전후',
    desc: '한국 상장 기업의 실적 발표 전후 주가-이벤트 분석 대시보드 (종목별).',
    tag: 'CLOUD',
    status: 'pending',
    reason: 'DART 정기공시 접수일 + KRX 주가 데이터로 구현 가능합니다. KRX Open API 인증키가 있으면 연동됩니다.',
  },
];

if (typeof module !== 'undefined') module.exports = CARDS;
