// 대시보드 카드 정의. status: 'live' | 'pending'
// pending 카드는 reason 필드로 사유를 표시한다.
// category: 그리드를 섹션으로 묶는 분류. usage: 이 데이터를 투자에 어떻게 쓰는지 설명(고정 텍스트).
// 실제 수치에 따라 달라지는 해석은 js/insights.js가 실시간으로 계산한다.

const CATEGORIES = [
  { id: 'flow', label: '국내 수급 · 경보', accent: '#1baf7a' },
  { id: 'derivatives', label: '파생상품', accent: '#eda100' },
  { id: 'corporate', label: '기업 이벤트 · 공시', accent: '#e87ba4' },
  { id: 'etf', label: 'ETF · 지수', accent: '#008300' },
  { id: 'us', label: '미국 시장', accent: '#4a3aa7' },
  { id: 'macro', label: '매크로', accent: '#eb6834' },
];

const CARDS = [
  {
    id: 'short-selling',
    icon: '📉',
    category: 'flow',
    title: '한국 공매도',
    desc: '거래대금 상위 종목의 당일 공매도 비중 랭킹 (코스피+코스닥).',
    usage: '공매도 비중이 높은 종목은 하락에 베팅한 자금이 몰려있다는 뜻입니다. 주가가 예상과 달리 오르면 공매도 투자자들이 손실을 줄이려 급하게 되사는 "숏커버링"이 터지며 단기 급등이 나올 수 있고, 반대로 계속 밀리면 추가 매도 압력의 신호가 됩니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'short-selling.json',
    render: 'renderShortSelling',
  },
  {
    id: 'alert-screener',
    icon: '⚡',
    category: 'flow',
    title: '투자주의/경고 스크리너',
    desc: 'KRX KIND 공시 기반 투자주의/경고/위험 종목 지정 내역 (최근 2주).',
    usage: '단기 급등락이나 이상거래로 거래소가 직접 경고를 붙인 종목입니다. 투자경고·위험 종목으로 갈수록 신용거래 제한, 매매거래 정지 위험이 커지므로 보유 중이라면 비중 축소를, 신규 진입이라면 변동성 확대를 각오해야 합니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'market-alerts.json',
    render: 'renderMarketAlerts',
  },
  {
    id: 'investor-flow',
    icon: '🔄',
    category: 'flow',
    title: '수급 주체 전환 스크리너',
    desc: '외국인·기관·연기금·개인 순매수대금. 최근 3거래일 vs 직전 5거래일 매수/매도 전환 종목.',
    usage: '외국인·기관처럼 정보 우위가 있다고 여겨지는 주체의 매매 방향이 바뀌는 순간은 추세 전환의 선행 신호로 자주 인용됩니다. 매도에서 매수로 전환된 종목은 저가 매수 관점으로, 매수에서 매도로 전환된 종목은 차익실현·이탈 신호로 볼 수 있습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'investor-flow.json',
    render: 'renderInvestorFlow',
  },
  {
    id: 'futures-oi',
    icon: '📐',
    category: 'derivatives',
    title: '주식선물 미결제약정 현황',
    desc: 'KRX 주식선물 종목의 미결제약정 잔량 랭킹과 전일대비 증감.',
    usage: '미결제약정(OI)은 시장에 남아있는 선물 포지션의 크기입니다. 주가 상승과 함께 OI가 늘면 신규 매수세 유입(추세 지속 가능성), 주가 하락과 함께 OI가 늘면 신규 매도(공매도성) 유입으로 해석하는 것이 기본 원칙입니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-oi.json',
    render: 'renderFuturesOi',
  },
  {
    id: 'futures-basis',
    icon: '📏',
    category: 'derivatives',
    title: '주식선물 베이시스 (콘탱고/백워데이션)',
    desc: '선물 상장 종목의 선물가 vs 현물가 괴리율. 콘탱고·백워데이션 상위 종목.',
    usage: '베이시스가 비정상적으로 벌어지면(콘탱고 확대) 프로그램 매수차익거래 유입 기대감, 반대로 백워데이션이 깊어지면 현물 매도·수급 악화 신호로 해석됩니다. 선물 만기가 가까울수록 베이시스는 0으로 수렴하는 경향이 있다는 점도 함께 참고하세요.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-basis.json',
    render: 'renderFuturesBasis',
  },
  {
    id: 'capital-increase',
    icon: '🏢',
    category: 'corporate',
    title: '유무상증자 기준일',
    desc: 'DART 전자공시 수집으로 유상증자·무상증자·주주배정 기준일을 정리.',
    usage: '유상증자는 발행가만큼 할인되어 신주가 풀리므로 단기적으로 주가엔 희석·하락 압력입니다. 반대로 무상증자는 유통주식수가 늘며 유동성이 좋아진다는 기대로 기준일 전후 단기 상승이 나오는 경우가 많아 신주배정기준일을 캘린더에 체크해두는 것이 좋습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: ['dart-capital-increase-paid.json', 'dart-capital-increase-free.json'],
    render: 'renderCapitalIncrease',
  },
  {
    id: 'convertible-bond',
    icon: '🔁',
    category: 'corporate',
    title: '전환청구권 신주상장 캘린더',
    desc: 'CB(전환사채) 발행 결정 공시를 수집해 전환가액·전환청구기간을 캘린더로 정리.',
    usage: '전환청구기간이 열리면 CB 투자자가 주식으로 바꿔 파는 물량이 잠재적 매도 대기물량(오버행)이 됩니다. 특히 현재가가 전환가액보다 높을수록 전환 후 즉시 차익매도 유인이 커지므로, 전환가액과 현재가를 비교해두면 단기 매물 출회 시점을 가늠할 수 있습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-convertible-bond.json',
    render: 'renderConvertibleBond',
  },
  {
    id: 'treasury-stock',
    icon: '💰',
    category: 'corporate',
    title: '자사주 매입 캘린더',
    desc: 'DART 자사주 신고·체결내역과 주요사항 보고서를 걸어, 지금 자사주를 사고 있거나 앞으로 살 계획인 회사를 취득기간 캘린더로 정리.',
    usage: '자사주 취득은 회사가 자기 주식을 사들여 유통물량을 줄이는 것이라 통상 주가에 우호적 신호(저평가 인식, 주주환원 의지)로 읽힙니다. 반대로 처분 공시는 잠재 매도물량 증가이니, 취득기간이 "진행 중"인 종목과 "처분 예정"인 종목을 구분해서 봐야 합니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-treasury-stock.json',
    render: 'renderTreasuryStock',
  },
  {
    id: 'insider-plan',
    icon: '👤',
    category: 'corporate',
    title: '내부자 사전공시',
    desc: '임원·주요주주 거래계획보고서(자본시장법 §173의3)를 수집해 거래 예정기간을 캘린더로 정리.',
    usage: '회사 내부 사정을 가장 잘 아는 임원·주요주주의 매매 계획입니다. 매수 계획 공시는 회사 전망에 대한 자신감으로, 대규모 매도 계획은 차익실현이거나 경계 신호로 해석하는 투자자가 많습니다. 다만 개인적 자금 사정(세금, 상속 등)일 수도 있어 매도=악재로 단정하지는 마세요.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-insider-plan.json',
    render: 'renderInsiderPlan',
  },
  {
    id: 'kr-earnings',
    icon: '🇰🇷',
    category: 'corporate',
    title: 'KR 기업 실발 전후',
    desc: '영업(잠정)실적 공정공시 기업의 발표 전후 주가 반응 (DART + KRX).',
    usage: '실적 발표 직후 주가가 기대만큼 안 움직이거나 오히려 반대로 가면 "이미 주가에 선반영됐거나(재료 소멸)" 시장이 다른 부분(가이던스, 비용구조 등)에 실망했다는 뜻입니다. D+1~D+4 반응이 같은 방향으로 이어지는지(추세화) 아니면 하루 만에 되돌리는지(뇌동매매)를 함께 보세요.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'kr-earnings-reaction.json',
    render: 'renderKrEarnings',
  },
  {
    id: 'etf-rebalance-schedule',
    icon: '🗓️',
    category: 'etf',
    title: '패시브 ETF 정기변경 일정',
    desc: 'KOSPI200·KOSDAQ150·MSCI Korea 등 주요 지수 정기변경 주기 캘린더.',
    usage: '지수 정기변경 시행일 직전에는 편입이 예상되는 종목에 패시브 자금이 선반영되어 몰리고, 실제 편입일에는 오히려 "뉴스에 팔아라"로 단기 고점이 되는 경우가 흔합니다. 편출 예상 종목은 반대로 시행일까지 매도 수급에 노출됩니다.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'index-rebalance-calendar.json',
    render: 'renderIndexCalendar',
  },
  {
    id: 'sector-etf-rebalance',
    icon: '🏛️',
    category: 'etf',
    title: '섹터/테마 ETF 리밸런싱 감지',
    desc: '국내 섹터·테마 ETF 상위 25종의 전일 대비 구성종목 변화(신규 편입/편출·비중 변동) 감지.',
    usage: '여러 테마 ETF에 동시다발적으로 신규 편입되는 종목은 패시브 매수 자금이 몰리는 초입일 수 있습니다. 반대로 여러 ETF에서 동시에 비중이 줄거나 편출되면 구조적 매도 수급으로 이어질 수 있으니 개별 종목 재료와 함께 교차 확인하세요.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'etf-rebalance-detect.json',
    render: 'renderEtfRebalance',
  },
  {
    id: 'us-market-brief',
    icon: '🌙',
    category: 'us',
    title: '전일 미국장 시황 브리핑',
    desc: '간밤 미국 증시 시황 요약 브리핑. 주요 지수·금리·환율·원자재 자동 수집.',
    usage: '한국 증시는 개장 전 간밤 미국장 흐름을 따라가는 경향이 뚜렷합니다. 나스닥이 강했다면 국내 반도체·성장주에, 금리·환율 급변은 은행·수출주에 영향을 주므로 개장 전 반드시 체크하는 것이 좋습니다. VIX 급등은 위험자산 전반의 변동성 확대 신호입니다.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'us-market-brief.json',
    render: 'renderMarketBrief',
  },
  {
    id: 'us-new-highs-20d',
    icon: '📈',
    category: 'us',
    title: 'US 미국장 20일 신고가',
    desc: 'S&P500 전종목 중 20일 신고가 경신 종목 스크리너.',
    usage: '신고가 경신은 매수세가 매도세를 압도하고 있다는 가장 단순하고 강력한 추세 신호입니다. 신고가 종목 수가 시장 전체적으로 늘어나면 강세장 폭이 넓다는 뜻이고, 소수 종목에만 몰리면 쏠림이 심하다는 경고로도 읽을 수 있습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-20d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'us-new-highs-50d',
    icon: '🏦',
    category: 'us',
    title: '미국장 50일 신고가 (대형주)',
    desc: '다우30 + 나스닥100 대형주 중 50일 신고가 경신 종목 스크리너.',
    usage: '대형주의 50일 신고가는 단기 노이즈보다 중기 추세를 반영합니다. 시가총액이 큰 종목이 신고가를 낸다는 건 그만큼 큰 자금이 장기간 꾸준히 유입되고 있다는 뜻이라 스윙·중기 매매 후보군으로 참고하기 좋습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-50d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'nvda-earnings',
    icon: '🎯',
    category: 'us',
    title: '엔비디아 실적 전후 등락률',
    desc: 'NVDA 실적 발표를 D+0으로 놓고 D-1~D+4 동안 NVDA·SOXX·SK하이닉스·삼성전자·코스피가 어떻게 움직였는지 최근 분기를 비교.',
    usage: 'NVDA는 AI·반도체 밸류체인의 풍향계 역할을 합니다. NVDA 실적 후 반응이 SOXX·SK하이닉스·삼성전자로 얼마나 강하게 전이되는지를 보면, 다음 분기 국내 반도체 소부장·메모리 종목의 실적 발표 전후 변동성을 미리 가늠하는 데 참고할 수 있습니다.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'nvda-earnings-reaction.json',
    render: 'renderNvdaEarnings',
  },
  {
    id: 'us-earnings',
    icon: '🇺🇸',
    category: 'us',
    title: 'US 기업 실발 전후',
    desc: '시총 20억달러 이상 미국 기업의 최근 실적 발표 전후 주가 반응.',
    usage: '서프라이즈(%)와 실제 주가 반응의 방향이 다르면(어닝비트인데 주가 하락 등) 가이던스나 시장 기대치와의 괴리 때문인 경우가 많습니다. 같은 업종 여러 종목의 반응을 묶어 보면 개별 기업 이슈인지 업종 전반의 재평가인지 구분할 수 있습니다.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'us-earnings-reaction.json',
    render: 'renderUsEarnings',
  },
  {
    id: 'export-data',
    icon: '📦',
    category: 'macro',
    title: '수출데이터 일평균',
    desc: '관세청(TRASS) 잠정 수출 33개 품목을 영업일 평균 기준으로 추적.',
    usage: '수출은 한국 상장기업 실적의 선행지표입니다. 반도체·자동차 등 주력 품목의 일평균 수출액 증가율은 관련 대형주의 다음 분기 실적 추정치를 조정하는 데 참고자료로 널리 쓰입니다.',
    tag: 'LIVE',
    status: 'pending',
    reason: 'TRASS(무역통계) 웹사이트는 봇 방지 토큰이 걸려 있어 자동 수집이 불가합니다. 공공데이터포털(data.go.kr)에서 "관세청 수출입무역통계" API를 무료 신청해 키를 알려주시면 바로 연동합니다.',
  },
];

if (typeof module !== 'undefined') module.exports = { CARDS, CATEGORIES };
