// 대시보드 카드 정의. status: 'live' | 'pending'
// pending 카드는 reason 필드로 사유를 표시한다.
const CARDS = [
  {
    id: 'short-selling',
    icon: '📉',
    title: '한국 공매도',
    desc: '거래대금 상위 종목의 당일 공매도 비중 랭킹 (코스피+코스닥).',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'short-selling.json',
    render: 'renderShortSelling',
  },
  {
    id: 'alert-screener',
    icon: '⚡',
    title: '투자주의/경고 스크리너',
    desc: 'KRX KIND 공시 기반 투자주의/경고/위험 종목 지정 내역 (최근 2주).',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'market-alerts.json',
    render: 'renderMarketAlerts',
  },
  {
    id: 'futures-oi',
    icon: '📐',
    title: '주식선물 미결제약정 현황',
    desc: 'KRX 주식선물 종목의 미결제약정 잔량 랭킹과 전일대비 증감.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-oi.json',
    render: 'renderFuturesOi',
  },
  {
    id: 'futures-basis',
    icon: '📏',
    title: '주식선물 베이시스 (콘탱고/백워데이션)',
    desc: '선물 상장 종목의 선물가 vs 현물가 괴리율. 콘탱고·백워데이션 상위 종목.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'krx-futures-basis.json',
    render: 'renderFuturesBasis',
  },
  {
    id: 'investor-flow',
    icon: '🔄',
    title: '수급 주체 전환 스크리너',
    desc: '외국인·기관·연기금·개인 순매수대금. 최근 3거래일 vs 직전 5거래일 매수/매도 전환 종목.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'investor-flow.json',
    render: 'renderInvestorFlow',
  },
  {
    id: 'nvda-earnings',
    icon: '🎯',
    title: '엔비디아 실적 전후 등락률',
    desc: 'NVDA 실적 발표를 D+0으로 놓고 D-1~D+4 동안 NVDA·SOXX·SK하이닉스·삼성전자·코스피가 어떻게 움직였는지 최근 분기를 비교.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'nvda-earnings-reaction.json',
    render: 'renderNvdaEarnings',
  },
  {
    id: 'etf-rebalance-schedule',
    icon: '🗓️',
    title: '패시브 ETF 정기변경 일정',
    desc: 'KOSPI200·KOSDAQ150·MSCI Korea 등 주요 지수 정기변경 주기 캘린더.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'index-rebalance-calendar.json',
    render: 'renderIndexCalendar',
  },
  {
    id: 'sector-etf-rebalance',
    icon: '🏛️',
    title: '섹터/테마 ETF 리밸런싱 감지',
    desc: '국내 섹터·테마 ETF 상위 25종의 전일 대비 구성종목 변화(신규 편입/편출·비중 변동) 감지.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'etf-rebalance-detect.json',
    render: 'renderEtfRebalance',
  },
  {
    id: 'export-data',
    icon: '📦',
    title: '수출데이터 일평균',
    desc: '관세청(TRASS) 잠정 수출 33개 품목을 영업일 평균 기준으로 추적.',
    tag: 'LIVE',
    status: 'pending',
    reason: 'TRASS(무역통계) 웹사이트는 봇 방지 토큰이 걸려 있어 자동 수집이 불가합니다. 공공데이터포털(data.go.kr)에서 "관세청 수출입무역통계" API를 무료 신청해 키를 알려주시면 바로 연동합니다.',
  },
  {
    id: 'capital-increase',
    icon: '🏢',
    title: '유무상증자 기준일',
    desc: 'DART 전자공시 수집으로 유상증자·무상증자·주주배정 기준일을 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: ['dart-capital-increase-paid.json', 'dart-capital-increase-free.json'],
    render: 'renderCapitalIncrease',
  },
  {
    id: 'convertible-bond',
    icon: '🔁',
    title: '전환청구권 신주상장 캘린더',
    desc: 'CB(전환사채) 발행 결정 공시를 수집해 전환가액·전환청구기간을 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-convertible-bond.json',
    render: 'renderConvertibleBond',
  },
  {
    id: 'treasury-stock',
    icon: '💰',
    title: '자사주 매입 캘린더',
    desc: 'DART 자사주 신고·체결내역과 주요사항 보고서를 걸어, 지금 자사주를 사고 있거나 앞으로 살 계획인 회사를 취득기간 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-treasury-stock.json',
    render: 'renderTreasuryStock',
  },
  {
    id: 'insider-plan',
    icon: '👤',
    title: '내부자 사전공시',
    desc: '임원·주요주주 거래계획보고서(자본시장법 §173의3)를 수집해 거래 예정기간을 캘린더로 정리.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'dart-insider-plan.json',
    render: 'renderInsiderPlan',
  },
  {
    id: 'us-market-brief',
    icon: '🌙',
    title: '전일 미국장 시황 브리핑',
    desc: '간밤 미국 증시 시황 요약 브리핑. 주요 지수·금리·환율·원자재 자동 수집.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'us-market-brief.json',
    render: 'renderMarketBrief',
  },
  {
    id: 'us-new-highs-20d',
    icon: '📈',
    title: 'US 미국장 20일 신고가',
    desc: 'S&P500 전종목 중 20일 신고가 경신 종목 스크리너.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-20d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'us-new-highs-50d',
    icon: '🏦',
    title: '미국장 50일 신고가 (대형주)',
    desc: '다우30 + 나스닥100 대형주 중 50일 신고가 경신 종목 스크리너.',
    tag: 'LIVE',
    status: 'live',
    dataFile: 'us-new-highs-50d.json',
    render: 'renderNewHighs',
  },
  {
    id: 'us-earnings',
    icon: '🇺🇸',
    title: 'US 기업 실발 전후',
    desc: '시총 20억달러 이상 미국 기업의 최근 실적 발표 전후 주가 반응.',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'us-earnings-reaction.json',
    render: 'renderUsEarnings',
  },
  {
    id: 'kr-earnings',
    icon: '🇰🇷',
    title: 'KR 기업 실발 전후',
    desc: '영업(잠정)실적 공정공시 기업의 발표 전후 주가 반응 (DART + KRX).',
    tag: 'CLOUD',
    status: 'live',
    dataFile: 'kr-earnings-reaction.json',
    render: 'renderKrEarnings',
  },
];

if (typeof module !== 'undefined') module.exports = CARDS;
